### ISSUE TITLE
docker 启动失败啊

### ISSUE THREAD

**Issue by hqdun69** [hanc00l/nemo_go#1]

**Comment by hanc00l** [comment]
刚重新build了一下，应该是mysql数据库的问题，初看了一下应该是mysql更新到mysql5.7.35后，默认root用户是无法登录的，如果是虚拟机或vps安装可参考install_linux.md文档；后续我重新调整和测试一下Dockerfile再fix。

**Comment by hanc00l** [comment]
修改docker的使用方式为docker-compose方式，已更新并Fix。
