### ISSUE TITLE
希望可以加个目录扫描功能

### ISSUE THREAD

**Issue by gdft2112** [hanc00l/nemo_go#10]
希望可以加个目录扫描功能，如果不行的话当我没说😂

**Comment by hanc00l** [comment]
在2.4.11中已增加[dirsearch](https://github.com/evilsocket/dirsearch)功能。

加入目录遍历功能代码量不大，不过必要性我是踌躇了很久；在实战中，使用中主动扫描（pocsuite、xray及dirsearch）因为带有明显的攻击payload，导致被安全设备BAN掉IP的概率相当大，所以建议谨慎使用。
