### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by SiYuan-Rao** [hanc00l/nemo_go#103]
能不能指定Worker做对应的任务，比如有些部署Worker只用来进行漏扫。用于信息收集的Worker设置较慢的扫描速度以及尽可能进行被动信息收集。这样就可以尽可能的避免出现因为漏扫导致信息收集不全的情况。

**Comment by hanc00l** [comment]
目前还没有实现，不过已考虑过，后续会完善功能，感谢支持。

**Comment by hanc00l** [comment]
v2.10.0已升级，使用请见安装手册。
