### ISSUE TITLE
求助贴

### ISSUE THREAD

**Issue by SiYuan-Rao** [hanc00l/nemo_go#104]
求助帖：
worker容器查看日志：
{"file":"daemon.go","func":"comm.StartWorkerDaemon","level":"error","msg":"deamon keep alive fail","time":"2023-07-16 22:10:45"}
{"file":"daemon.go","func":"comm.StartWorkerDaemon","level":"error","msg":"deamon keep alive fail","time":"2023-07-16 22:10:46"}
{"file":"daemon.go","func":"comm.StartWorkerDaemon","level":"error","msg":"deamon keep alive fail","time":"2023-07-16 22:10:46"}
{"file":"daemon.go","func":"comm.StartWorkerDaemon","level":"error","msg":"deamon keep alive fail","time":"2023-07-16 22:10:46"}
{"file":"keepalive.go","func":"comm.DoKeepAlive","level":"error","msg":"keep alive fail:invalid token","time":"2023-07-16 22:10:46"}
{"file":"main.go","func":"main.keepAlive","level":"error","msg":"keep alive fail","time":"2023-07-16 22:10:46"}
{"file":"daemon.go","func":"comm.StartWorkerDaemon","level":"error","msg":"deamon keep alive fail","time":"2023-07-16 22:10:46"}
{"file":"daemon.go","func":"comm.StartWorkerDaemon","level":"error","msg":"deamon keep alive fail","time":"2023-07-16 22:10:47"}
{"file":"daemon.go","func":"comm.StartWorkerDaemon","level":"error","msg":"deamon keep alive fail","time":"2023-07-16 22:10:47"}
{"file":"daemon.go","func":"comm.StartWorkerDaemon","level":"error","msg":"deamon keep alive fail","time":"2023-07-16 22:10:47"}
{"file":"keepalive.go","func":"comm.DoKeepAlive","level":"error","msg":"keep alive fail:invalid token","time":"2023-07-16 22:10:47"}
{"file":"main.go","func":"main.keepAlive","level":"error","msg":"keep alive fail","time":"2023-07-16 22:10:47"}
{"file":"daemon.go","func":"comm.StartWorkerDaemon","level":"error","msg":"deamon keep alive fail","time":"2023-07-16 22:10:47"}
{"file":"daemon.go","func":"comm.StartWorkerDaemon","level":"error","msg":"deamon keep alive fail","time":"2023-07-16 22:10:48"}
{"file":"daemon.go","func":"comm.StartWorkerDaemon","level":"error","msg":"deamon keep alive fail","time":"2023-07-16 22:10:48"}
{"file":"daemon.go","func":"comm.StartWorkerDaemon","level":"error","msg":"deamon keep alive fail","time":"2023-07-16 22:10:48"}
{"file":"keepalive.go","func":"comm.DoKeepAlive","level":"error","msg":"keep alive fail:invalid token","time":"2023-07-16 22:10:48"}
{"file":"main.go","func":"main.keepAlive","level":"error","msg":"keep alive fail","time":"2023-07-16 22:10:48"}
{"file":"daemon.go","func":"comm.StartWorkerDaemon","level":"error","msg":"deamon keep alive fail","time":"2023-07-16 22:10:48"}
{"file":"daemon.go","func":"comm.StartWorkerDaemon","level":"error","msg":"deamon keep alive fail","time":"2023-07-16 22:10:49"}
{"file":"daemon.go","func":"comm.StartWorkerDaemon","level":"error","msg":"deamon keep alive fail","time":"2023-07-16 22:10:49"}
{"file":"daemon.go","func":"comm.StartWorkerDaemon","level":"error","msg":"deamon keep alive fail","time":"2023-07-16 22:10:49"}

**Comment by SiYuan-Rao** [comment]
worker.yml 填写的配置如下：
![Uploading WechatIMG1509.png…]()

**Comment by SiYuan-Rao** [comment]
worker.yml配置如下：
rpc:
  host: 119.x.x.x
  port: 5001
  authKey: uQ9jC8rI5pY6rR3kV9tY
fileSync:
  host: 119.x.x.x
  port: 5002
  authKey: uQ9jC8rI5pY6rR3kV9tY
rabbitmq:
  host: 119.x.x.x
  port: 5672
  username: Sxxxxxx
  password: uQ9jC8rI5pY6rR3kV9tY

**Comment by hanc00l** [comment]
从日志上看，应该是worker与server的的rpc通信失败，请检查一下server 119.x.x.x的5001端口是否开放、authKey是否一致。

**Comment by SiYuan-Rao** [comment]
解决了，谢谢大佬。server 容器里的配置没改过来，我手动改过来后重启就好了。
