### ISSUE TITLE
疑惑

### ISSUE THREAD

**Issue by SiYuan-Rao** [hanc00l/nemo_go#105]
我在勾选了端口扫描-IP扫描按钮，但是子域名收集完之后并没有进行端口扫描。在IP处查看只有空间搜索引擎上端口信息。没太理解，是我操作问题吗？
<img width="498" alt="image" src="https://github.com/hanc00l/nemo_go/assets/74602775/621de6e0-51c6-42c7-a86f-49b124594a92">

**Comment by hanc00l** [comment]
感谢反馈！
确实是一个BUG，应该是重构代码的时候没有进行完全测试，已找到原因，今天会修复和更新。

![WechatIMG11402](https://github.com/hanc00l/nemo_go/assets/12759172/0ffb8542-1cdc-453b-9d69-5bf3a750e1e4)

**Comment by hanc00l** [comment]
已修复并在release里更新。

如果是VPS部署，替换worker上的worker_linux_amd64即可。最方便的是将该文件在server上替换掉，并在dashboard重启worker即可自动同步。
如果是docker，建议删除容器和镜像后再重新构建。
