### ISSUE TITLE
大佬 如何设置msscan全端口

### ISSUE THREAD

**Issue by guanglianniubi** [hanc00l/nemo_go#106]
![图片](https://github.com/hanc00l/nemo_go/assets/45590232/daa5ab56-4d25-48fe-bd46-0cb0af08bd79)

**Comment by guanglianniubi** [comment]
那-sS那块不用管对吧，还有就是想问一下，有没有向灯塔那样扫描文件路径的 比如nacos，也不至于去漏洞探测，因为这往往是一个切入点，有相关群聊交流吗

**Comment by guanglianniubi** [comment]
fingerprint在同一任务下还会切分成几个任务，不好提取url

**Comment by hanc00l** [comment]
> 那-sS那块不用管对吧，还有就是想问一下，有没有向灯塔那样扫描文件路径的 比如nacos，也不至于去漏洞探测，因为这往往是一个切入点，有相关群聊交流吗

nemo主要还是以信息收集为主，扫描文件路径的行为在实战中大概率容易被BAN不太建议使用。在授权测试中或内网中，可以使用nemo集成的goby、xray、nuclei及dirsearch功能作为漏洞扫描（该功能仅作为信息收集的补充）。

分享nemo是因为遵循开源和共享精神，不太偏向推广和商业性；欢迎大家提出好的建议，也欢迎在遵守开源协议的基础上进行二次开发。因精力有限，没有群聊；如果有bug或建议，欢迎提issue。
