### ISSUE TITLE
docker拉不到镜像捏

### ISSUE THREAD

**Issue by jingke666** [hanc00l/nemo_go#107]
![image](https://github.com/hanc00l/nemo_go/assets/83952182/36a60862-22d6-469e-b31b-13424c5c3534)

**Comment by hanc00l** [comment]
我本地测试是OK的，你检查一下你的docker或者换个linux试试。
<img width="833" alt="iShot_2023-07-19_08 51 07" src="https://github.com/hanc00l/nemo_go/assets/12759172/d774cca6-7c77-4647-b3c1-785ab28592c0">
