### ISSUE TITLE
quake查询结果为空

### ISSUE THREAD

**Issue by jack-reso** [hanc00l/nemo_go#109]
当使用quake进行搜索时，不管搜什么ip都没有结果返回？但是在quake里是有结果的。
是因为系统只读取了某几个字段吗？
quake的key测试也是成功的

**Comment by hanc00l** [comment]
感谢支持Nemo！
经过测试已发现问题并修复，可以更新一下worker_linux_amd64文件即可。

**Comment by jack-reso** [comment]
好像还是不行
![image](https://github.com/hanc00l/nemo_go/assets/112871294/cc1e27eb-6891-4db6-8a6a-4c9722af64fe)

**Comment by jack-reso** [comment]
@hanc00l

**Comment by hanc00l** [comment]
一是确保quake的Key是正确有效，二是替换worker_linux_amd64这个文件（在release包里已更新）。

这是我刚才测试的效果：
<img width="1754" alt="iShot_2023-07-25_21 50 03" src="https://github.com/hanc00l/nemo_go/assets/12759172/479049b8-66dd-4adf-bc7b-1110364a6689">
<img width="1655" alt="iShot_2023-07-25_21 52 55" src="https://github.com/hanc00l/nemo_go/assets/12759172/fba792e2-5a19-416d-b5c9-06d22432cd16">
