### ISSUE TITLE
如何导出所有的web站点？

### ISSUE THREAD

**Issue by testa010** [hanc00l/nemo_go#111]
大佬，有什么接口能导出httpx识别到的所有web站点吗？

**Comment by hanc00l** [comment]
> 大佬，有什么接口能导出httpx识别到的所有web站点吗？

目前Nemo提供了简单的统计功能（用于将收集的信息用于其它工具），还没有直接将资产导出的功能。 如果需要导出资产，建议用py脚本连接数据库，读取相应的ip/domain表，以及各属性值进行处理后生成自已需要的信息。

**Comment by testa010** [comment]
> > 大佬，有什么接口能导出httpx识别到的所有web站点吗？
> 
> 目前Nemo提供了简单的统计功能（用于将收集的信息用于其它工具），还没有直接将资产导出的功能。 如果需要导出资产，建议用py脚本连接数据库，读取相应的ip/domain表，以及各属性值进行处理后生成自已需要的信息。

后续考虑更新该功能吗，增加导出子域名、导出web站点的接口，会方便很多~~

**Comment by hanc00l** [comment]
v2.10.0已新增导出资产的功能。
