### ISSUE TITLE
请问新建Xscan任务为什么还要在枚举一遍子域名啊

### ISSUE THREAD

**Issue by zaneSSS** [hanc00l/nemo_go#113]
资产探测的时候应该都探测完子域名了，新建xscan还要枚举子域名是不是重复了，可以取消吗

**Comment by hanc00l** [comment]
如果是资产已经探测过了，用XSCAN的话选择按“组织”方式（前提是在前前期探测的时候指定了组织）；XScan的设计就是从IP/Domain任务-指纹探测-漏洞验证的全流程。
XScan的IP/Domain执行的任务，是在配置里指定的。
<img width="503" alt="iShot_2023-08-13_08 54 17" src="https://github.com/hanc00l/nemo_go/assets/12759172/a679e018-32d6-45a6-a450-a7729e339f22">
<img width="1248" alt="iShot_2023-08-13_08 51 49" src="https://github.com/hanc00l/nemo_go/assets/12759172/37b1b78d-6451-4715-9baa-59ef005097ad">
<img width="903" alt="iShot_2023-08-13_08 52 52" src="https://github.com/hanc00l/nemo_go/assets/12759172/89690ef5-b248-4fb5-9de4-37a13c8af1a6">

**Comment by hanc00l** [comment]
可以看看代码的实现，Xscan选择“组织”的时候是不会执行子域名的任务的：
<img width="1148" alt="iShot_2023-08-13_09 09 17" src="https://github.com/hanc00l/nemo_go/assets/12759172/821302a0-fe1a-49b3-b05f-2f57b433376b">
<img width="967" alt="iShot_2023-08-13_09 09 37" src="https://github.com/hanc00l/nemo_go/assets/12759172/92cdf01b-4a99-4e40-9558-32c1810d86db">

**Comment by zaneSSS** [comment]
好的多谢！看明白了
