### ISSUE TITLE
Xscan选择组织任务中断【bug】

### ISSUE THREAD

**Issue by zaneSSS** [hanc00l/nemo_go#114]
试了好几次组织内域名共700多个，选择xscan内的组织漏洞扫描，勾选了xray和goby，Xxray和Xgoby会自动中断变成0/43/200 这种格式，restart镜像任务会继续启动过一段时间又会中止。去docker里面看了一下任务进程里都没有运行，不知道哪里卡住了。
难道是域名太多了吗
<img width="1237" alt="image" src="https://github.com/hanc00l/nemo_go/assets/44695853/8288bbc2-624d-4b7e-a100-43c422a526c0">
<img width="1318" alt="image" src="https://github.com/hanc00l/nemo_go/assets/44695853/1c2c3d79-d21f-4da5-9228-ae13541f91ba">

**Comment by hanc00l** [comment]
我本地测试了一下（非docker环境，3个域名）貌似正常。
<img width="1191" alt="iShot_2023-08-16_14 42 52" src="https://github.com/hanc00l/nemo_go/assets/12759172/1e3e1aa3-1294-4120-a63b-fc02748273ac">
<img width="1072" alt="iShot_2023-08-16_14 43 33" src="https://github.com/hanc00l/nemo_go/assets/12759172/c4ef21a0-1fbe-4e9c-b4c3-a018bfade398">
<img width="897" alt="iShot_2023-08-16_14 43 22" src="https://github.com/hanc00l/nemo_go/assets/12759172/eee363bb-df35-4e1a-b90c-381ef90391b0">

nemo有详细的任务执行的过程信息和日志，可结合起来看看是哪里出了问题。

**Comment by hanc00l** [comment]
只是xgoby任务有问题么？xxray任务是否正常？
