### ISSUE TITLE
大佬，导出的资产还是没有最关键的元素-url

### ISSUE THREAD

**Issue by guanglianniubi** [hanc00l/nemo_go#116]

**Comment by guanglianniubi** [comment]
domain的资产导出缺少httpx结果

**Comment by guanglianniubi** [comment]
而且domain导出资产的端口堆积在一起了

**Comment by guanglianniubi** [comment]
IP的资产导出就很舒服了

**Comment by hanc00l** [comment]
> domain的资产导出缺少httpx结果

之前考虑过但最终去掉了，需要的话自己把代码改一下自己生成一下。

**Comment by hanc00l** [comment]
> 而且domain导出资产的端口堆积在一起了

domain和ip不一样，domain没有单独关联每个端口。

**Comment by guanglianniubi** [comment]
我这样解决，将域名和端口单独提出来，然后找gpt写了个脚本，重新拼接了一下，

代码：
with open('file1.txt', 'r', encoding='utf-8') as file1, \
     open('file2.txt', 'r', encoding='utf-8') as file2, \
     open('output.txt', 'w', encoding='utf-8') as output_file:
    lines_file1 = file1.readlines()
    lines_file2 = file2.readlines()

    for line1, line2 in zip(lines_file1, lines_file2):
        line1 = line1.strip()  # 移除换行符等空白字符
        line2 = line2.strip()  # 移除换行符等空白字符

        if ',' in line2:  # 如果第二个文本行包含逗号
            parts = line2.split(',')  # 以逗号分隔
            for part in parts:
                output_file.write(line1 + ':' + part.strip() + '\n')  # 将每个部分添加到第一个文本行对应的文本行中
        else:
            output_file.write(line1 + ':' + line2 + '\n')  # 将第二个文本行直接添加到第一个文本行对应的文本行中

**Comment by hanc00l** [comment]
> 我这样解决，将域名和端口单独提出来，然后找gpt写了个脚本，重新拼接了一下，
> 
> 代码： with open('file1.txt', 'r', encoding='utf-8') as file1, open('file2.txt', 'r', encoding='utf-8') as file2, open('output.txt', 'w', encoding='utf-8') as output_file: lines_file1 = file1.readlines() lines_file2 = file2.readlines()
> 
> ```
> for line1, line2 in zip(lines_file1, lines_file2):
>     line1 = line1.strip()  # 移除换行符等空白字符
>     line2 = line2.strip()  # 移除换行符等空白字符
> 
>     if ',' in line2:  # 如果第二个文本行包含逗号
>         parts = line2.split(',')  # 以逗号分隔
>         for part in parts:
>             output_file.write(line1 + ':' + part.strip() + '\n')  # 将每个部分添加到第一个文本行对应的文本行中
>     else:
>         output_file.write(line1 + ':' + line2 + '\n')  # 将第二个文本行直接添加到第一个文本行对应的文本行中
> ```

是的，我也觉得这样挺好的。
