### ISSUE TITLE
大佬，怎么没法加fofa的token？

### ISSUE THREAD

**Issue by qazsewsxdredcft** [hanc00l/nemo_go#117]
大佬，我试了好几种模式，都测试失败了。
分别是
邮箱：cookie中的fofa_token
邮箱：fofa API key
cookie中的fofa_token
fofa API key
都显示测试失败了。。

**Comment by hanc00l** [comment]
FOFA需要用户的Email，格式为Email:KEY，比如：admin@163.com:abcdxxx1234

<img width="365" alt="iShot_2023-08-20_14 21 42" src="https://github.com/hanc00l/nemo_go/assets/12759172/e513ada8-4a27-4ae7-a121-ed9d63abacd4">
<img width="801" alt="iShot_2023-08-20_14 22 54" src="https://github.com/hanc00l/nemo_go/assets/12759172/043e6188-c83f-4fbb-ab75-df9f575b283a">
<img width="500" alt="iShot_2023-08-20_14 25 29" src="https://github.com/hanc00l/nemo_go/assets/12759172/6b362d7d-d24c-48e1-8f78-f0cb1d10fd90">

测试前一定要先保存配置。

**Comment by HiIK-666** [comment]
> FOFA需要用户的Email，格式为Email:KEY，比如：[admin@163.com](mailto:admin@163.com):abcdxxx1234
> 
> <img alt="iShot_2023-08-20_14 21 42" width="365" src="https://user-images.githubusercontent.com/12759172/261835233-e513ada8-4a27-4ae7-a121-ed9d63abacd4.png"> <img alt="iShot_2023-08-20_14 22 54" width="801" src="https://user-images.githubusercontent.com/12759172/261835236-043e6188-c83f-4fbb-ab75-df9f575b283a.png"> <img alt="iShot_2023-08-20_14 25 29" width="500" src="https://user-images.githubusercontent.com/12759172/261835286-6b362d7d-d24c-48e1-8f78-f0cb1d10fd90.png">
> 测试前一定要先保存配置。

搜索结果数量限制是否是单个TOKEN的 还是 总和 我有两个fofa ,是否是一个fofa token 搜索出我设定的数量?

**Comment by xxxxxxovo** [comment]
> 大佬，我试了好几种模式，都测试失败了。 分别是 邮箱：cookie中的fofa_token 邮箱：fofa API key cookie中的fofa_token fofa API key 都显示测试失败了。。



> FOFA需要用户的Email，格式为Email:KEY，比如：[admin@163.com](mailto:admin@163.com):abcdxxx1234
> <img alt="iShot_2023-08-20_14 21 42" width="365" src="https://user-images.githubusercontent.com/12759172/261835233-e513ada8-4a27-4ae7-a121-ed9d63abacd4.png"> <img alt="iShot_2023-08-20_14 22 54" width="801" src="https://user-images.githubusercontent.com/12759172/261835236-043e6188-c83f-4fbb-ab75-df9f575b283a.png"> <img alt="iShot_2023-08-20_14 25 29" width="500" src="https://user-images.githubusercontent.com/12759172/261835286-6b362d7d-d24c-48e1-8f78-f0cb1d10fd90.png">
> 
> 测试前一定要先保存配置。

大佬，我按照要求填写了key，也在woker.yml文件中添加了，重启了docker服务，但是开启扫描任务还是调用不了fofa，日志中提示找不到fofakey，求解
<img width="427" alt="6e01c2418100d8edd56f4dd97ff98d6" src="https://github.com/hanc00l/nemo_go/assets/142147430/1bc2b59f-3076-479c-a724-aedb5b5e8408">
<img width="521" alt="cb5aee260628992486fc934a9f3cb49" src="https://github.com/hanc00l/nemo_go/assets/142147430/6d81effd-2e0c-4a70-9eb4-13569f00b217">

**Comment by Lyf888lyf** [comment]
确实是按照要求配置，但没有用

**Comment by LING12138-sg** [comment]
> > 大佬，我试了好几种模式，都测试失败了。 分别是 邮箱：cookie中的fofa_token 邮箱：fofa API key cookie中的fofa_token fofa API key 都显示测试失败了。。
> 
> > FOFA需要用户的Email，格式为Email:KEY，比如：[admin@163.com](mailto:admin@163.com):abcdxxx1234
> > <img alt="iShot_2023-08-20_14 21 42" width="365" src="https://user-images.githubusercontent.com/12759172/261835233-e513ada8-4a27-4ae7-a121-ed9d63abacd4.png"> <img alt="iShot_2023-08-20_14 22 54" width="801" src="https://user-images.githubusercontent.com/12759172/261835236-043e6188-c83f-4fbb-ab75-df9f575b283a.png"> <img alt="iShot_2023-08-20_14 25 29" width="500" src="https://user-images.githubusercontent.com/12759172/261835286-6b362d7d-d24c-48e1-8f78-f0cb1d10fd90.png">
> > 测试前一定要先保存配置。
> 
> 大佬，我按照要求填写了key，也在woker.yml文件中添加了，重启了docker服务，但是开启扫描任务还是调用不了fofa，日志中提示找不到fofakey，求解 <img alt="6e01c2418100d8edd56f4dd97ff98d6" width="427" src="https://private-user-images.githubusercontent.com/142147430/273394683-1bc2b59f-3076-479c-a724-aedb5b5e8408.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDc4MTE0NDEsIm5iZiI6MTc0NzgxMTE0MSwicGF0aCI6Ii8xNDIxNDc0MzAvMjczMzk0NjgzLTFiYzJiNTlmLTMwNzYtNDc5Yy1hNzI0LWFlZGI1YjVlODQwOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDUyMVQwNzA1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMzUyYzIzNWYxZWZkZGU5ZDZjODJkY2ZkNzk1MWU1Nzc4N2JmZmIzMjBjOWVjMjc0MGEzNmIxODA3MWIwNWY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8kfVOMb5Osg7FJz9qIcTuUOwxfdsCVqXGzFfp7bv1Vg"> <img alt="cb5aee260628992486fc934a9f3cb49" width="521" src="https://private-user-images.githubusercontent.com/142147430/273394698-6d81effd-2e0c-4a70-9eb4-13569f00b217.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDc4MTE0NDEsIm5iZiI6MTc0NzgxMTE0MSwicGF0aCI6Ii8xNDIxNDc0MzAvMjczMzk0Njk4LTZkODFlZmZkLTJlMGMtNGE3MC05ZWI0LTEzNTY5ZjAwYjIxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDUyMVQwNzA1NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTg2ZTIxNjc4OTRkNDQ5Y2E0NDYxNTY5MmU2NmU5YzdiYjUzZDBiNDIyOTAzZjhhMjkzYWYyNGYwNDBhYjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IHOXZMcJO0bO485K-mvbYQJjvAB23tjpZQReNcw3fOk">

我也是这个问题，怎么解决啊？
