### ISSUE TITLE
希望可以加个页面js链接爬虫

### ISSUE THREAD

**Issue by Lengso** [hanc00l/nemo_go#12]
希望可以加个页面js链接爬虫

**Comment by Lengso** [comment]
另外网站截图功能建议用base64入库处理，不然会堆积
![image](https://user-images.githubusercontent.com/39323367/148086274-79b6d463-1dfb-462b-8b28-781ef8fcf385.png)

**Comment by hanc00l** [comment]
js页面爬取功能是在考虑的功能，只是目前还没有好的go实现，如果有好的方法或代码可以推荐一下我加进来；如果只是为了爬取子域名，目前已集成了crawlergo的源码实现。

网站截屏是worker采集后是统一上传到server的screenshot目录以文件形式保存的，worker只是临时文件最后应该会删除掉（刚检查了代码是遗漏了删除这一个步骤，会尽快修正这个问题）。

**Comment by Lengso** [comment]
积少成多这小机器都扛不住，worker机器上试过跑着跑着硬盘满了排查/tmp/snap.chromium/占了几十G

**Comment by hanc00l** [comment]
这个问题不排除实际中存在，目前还没遇到过，麻烦提供更详细一点的使用情况以便于分析、复现和改进，谢谢。

**Comment by Lengso** [comment]
大概排查了一下，我根据你提供的安装
