### ISSUE TITLE
[如果有bug或问题，请提Issue的时候，提供详细的使用说明便于改进和分析]域名导出来的端口是乱的

### ISSUE THREAD

**Issue by guanglianniubi** [hanc00l/nemo_go#123]

**Comment by hanc00l** [comment]
数据导出来是csv格式，如果是格式有点乱请用查看csv的工具打开，比如wps；端口的数据是由域名关联的ip下的端口中获得的。

**Comment by hanc00l** [comment]
如果有bug或问题，请提供详细的使用说明便于改进和分析

**Comment by guanglianniubi** [comment]
用wps打开的csv就如上面所说，转成txt格式后，逐行查看是正常的
![图片](https://github.com/hanc00l/nemo_go/assets/45590232/c62301f6-73f5-416b-987c-0771cd895339)

**Comment by hanc00l** [comment]
> 用wps打开的csv就如上面所说，转成txt格式后，逐行查看是正常的 ![图片](https://user-images.githubusercontent.com/45590232/266196552-c62301f6-73f5-416b-987c-0771cd895339.png)

csv格式是正常的，显示是wps的问题；你自己写个python脚本，调用csv直接读取和处理就行了。

**Comment by guanglianniubi** [comment]
csv格式不正常，端口是错的
![图片](https://github.com/hanc00l/nemo_go/assets/45590232/3897c05e-8ac6-4d28-8f0a-83191cb123b8)

**Comment by guanglianniubi** [comment]
大佬，subfinder配置完yml文件后怎么让他生效呢

**Comment by hanc00l** [comment]
配置了下一步调用subfinder就会生效。由于Server与worker默认是有文件同步功能的（可以在worker启动参数加-nf关闭），需要在server端修改thirdparty/dict/provider-config.yml文件；如果是在worker端修改的会被server端的文件同步后覆盖。
