### ISSUE TITLE
API Version

### ISSUE THREAD

**Issue by ch4O3** [hanc00l/nemo_go#13]
<img width="649" alt="image" src="https://user-images.githubusercontent.com/56219922/154028867-33ad1816-1af9-4787-9f89-e6b63ebc46fb.png">
API版本问题如何解决

**Comment by hanc00l** [comment]
请参考[https://stackoverflow.com/questions/59385378/when-running-docker-compose-i-get-client-version-1-38-is-too-new-maximum-suppo](https://stackoverflow.com/questions/59385378/when-running-docker-compose-i-get-client-version-1-38-is-too-new-maximum-suppo)上的问题。
