### ISSUE TITLE
漏洞页面提供批量删除功能

### ISSUE THREAD

**Issue by Conanjun** [hanc00l/nemo_go#133]
漏洞页面现在只能挨个删除

**Comment by Conanjun** [comment]
经常会扫的那种无关痛痒的，一出现就是一堆

**Comment by Conanjun** [comment]
漏洞筛选列表提供negative search功能是不是更好点，能排除掉一些不想看的漏洞类型

**Comment by hanc00l** [comment]
> 漏洞页面现在只能挨个删除

这个下次可以增加进来。

**Comment by hanc00l** [comment]
已增加了批量删除功能在2.10.3，欢迎测试。
