### ISSUE TITLE
关于新建用户的问题

### ISSUE THREAD

**Issue by dh-666** [hanc00l/nemo_go#139]
我用docker部署的，我想添加用户，但添加之后新用户无法登录。

**Comment by hanc00l** [comment]
添加用户后，要给用户指定workspace。（超级管理员可以管理全部不用指定）
<img width="611" alt="iShot_2023-11-16_15 05 24" src="https://github.com/hanc00l/nemo_go/assets/12759172/a8ce0ffa-9f5b-48c7-83b5-72fb3883beff">

**Comment by dh-666** [comment]
> 添加后用户，要给用户指定工作空间。（超级管理员可以管理全部不用指定） <img alt="iShot_2023-11-16_15 05 24" width="611" src="https://user-images.githubusercontent.com/12759172/283349945-a8ce0ffa-9f5b-48c7-83b5-72fb3883beff.png">
好的，感谢
