### ISSUE TITLE
大佬怎么添加了fofa那些的api，全部都没用呢

### ISSUE THREAD

**Issue by pytho1n** [hanc00l/nemo_go#19]

**Comment by hanc00l** [comment]
我用自己的api key试了正常的呀，建议你先在命令行下看看自己的key是否正常使用：
`echo 'domain="fofa.info"' | base64 - | xargs -I{} curl "https://fofa.info/api/v1/search/all?email=${FOFA_EMAIL}&key=${FOFA_KEY}&qbase64={}"
`

这是我用nemo测试的结果：

![截屏2022-03-25 16 50 49](https://user-images.githubusercontent.com/12759172/160089113-6dbada95-fb81-48a2-9730-244b34c0eec1.png)
![截屏2022-03-25 16 57 58](https://user-images.githubusercontent.com/12759172/160089140-6a783697-1da7-4df8-8d95-a4e5d5be7e4f.png)
![截屏2022-03-25 16 58 05](https://user-images.githubusercontent.com/12759172/160089163-6ae7be19-bf6e-4a56-9656-a2cff20e1ceb.png)
