### ISSUE TITLE
容易断网

### ISSUE THREAD

**Issue by H3ll0W0lrd** [hanc00l/nemo_go#20]
线程我worlk文件改了，是我改错地方了吗？但是还是以启动网络就GG了。

**Comment by hanc00l** [comment]
能说一下具体情况吗

**Comment by H3ll0W0lrd** [comment]
我是在本地搭建的，就是添加任务后开始扫描，不一会儿就访问不了网络了，然后qq、微信各种掉线。应该是Masscan扫描的线程大了或者其他调用工具的线程大了。

**Comment by hanc00l** [comment]
masscan扫描的速度建议控制一下，另外在做指纹识别和用headless-chrome截图时会有较大的并发流量，建议同时控制一个vps上的worker数量。

**Comment by H3ll0W0lrd** [comment]
> masscan扫描的速度建议控制一下，另外在做指纹识别和用headless-chrome截图时会有较大的并发流量，建议同时控制一个vps上的worker数量。

好的，多谢！
