### ISSUE TITLE
web无法访问

### ISSUE THREAD

**Issue by little-2pig** [hanc00l/nemo_go#22]
为何web服务都已监听，但web就是无法访问

**Comment by hanc00l** [comment]
麻烦提供详细的运行环境和问题截图，以便于分析原因。

**Comment by little-2pig** [comment]
您好，并无报错，就是docker运行起来后，web端口监听正常，就是web访问不到
kali：2022.1
docker：20.10.11+dfsg1
docker-compose：1.29.2
![image](https://user-images.githubusercontent.com/58223422/161177308-4f407c93-b468-4891-b3df-79d7d6b6e657.png)
![image](https://user-images.githubusercontent.com/58223422/161177788-c2ef071f-a95e-4cda-a569-e3a8f5a86004.png)

**Comment by zaintwk** [comment]
我也遇到了同样的问题，我怀疑是容器内的服务没有启动。因为我在容器内并没有发现5000端口的服务
![image](https://user-images.githubusercontent.com/65647071/166885749-f3115c04-3105-4a52-ab3b-0e0ad2990fab.png)

**Comment by hanc00l** [comment]
请确认是下载release的打包的nemo_linux_amd64.tar包解压后，用docker-compose进行构建；如果是用git clone或从github.com下载的zip包，是不包含编译后的可执行文件的。以前有同学遇到这种情况的。
刚刚了测试了kali的2022.1，用docker-compose构建正常运行。

**Comment by zaintwk** [comment]
谢谢 可以了，使用nemo_linux_amd64.tar包能进去了。希望后期能把docker的时区带上一下。现在用的还是美国时区

**Comment by hanc00l** [comment]
已在2.5.1中更新了docker时区的处理。
