### ISSUE TITLE
Subfinder如何添加Source key

### ISSUE THREAD

**Issue by okoling** [hanc00l/nemo_go#23]
rt

**Comment by hanc00l** [comment]
很抱歉，目前还不支持直接添加自定义的source key，可以参照github.com/projectdiscovery/subfinder直接修改代码添加。
如果有功能需求，后面可以将该功能增加进来。

**Comment by okoling** [comment]
建议在后台可以自定义添加Source key，不带key和带key获取的域名数量明显对比

**Comment by hanc00l** [comment]
没问题，近期将该功能代码增加到系统里。

**Comment by hanc00l** [comment]
v2.4.18已更新添加provider-config.yml文件增加自定义的source key，使用方法参见https://github.com/projectdiscovery/subfinder#post-installation-instructions。
