### ISSUE TITLE
./worker_darwin_amd64运行错误

### ISSUE THREAD

**Issue by jiangyuening** [hanc00l/nemo_go#24]
<img width="313" alt="截屏2022-04-12 18 23 26" src="https://user-images.githubusercontent.com/57979611/162940065-36263614-7ec9-4426-93a7-0731acf67e72.png">

**Comment by hanc00l** [comment]
应该是yml配置时格式不符合yml规范，建议你把配置文件发出来看看；或者了解一下yml的语法，看看是哪里出了错。
