### ISSUE TITLE
ERROR: Encountered errors while bringing up the project

### ISSUE THREAD

**Issue by Hhhnee** [hanc00l/nemo_go#25]
![图片](https://user-images.githubusercontent.com/84834363/163490802-5d0d835f-e8a2-405c-a8b8-38d5de36a98f.png)
这里换好了几台vps当客户机，后面单独搭建都是同样的报错。百度上说是冲突问题，可是docker-compose down了过后在up还是同样的问题
所以在想是不是配置文件弄错了
大大有空的话，麻烦帮我看一下。实在是弄了很久没搞定
![图片](https://user-images.githubusercontent.com/84834363/163491830-89795cca-e422-4f37-9910-84c73438a86f.png)

![图片](https://user-images.githubusercontent.com/84834363/163491792-1aaa719f-8b83-4f42-8403-633213cff4ce.png)

**Comment by hanc00l** [comment]
hunter配置里的key有点问题，yml格式的:后面要有一个空格。
key: 13b1....
