### ISSUE TITLE
mysql启动异常

### ISSUE THREAD

**Issue by nanioo** [hanc00l/nemo_go#26]
mysql启动异常，开了几次了，都没法启动，导致前段页面数据拉取失败
![mysql异常](https://user-images.githubusercontent.com/7869766/168530829-3f030a58-6de4-46ef-a210-bb317e6434dd.png)
![os](https://user-images.githubusercontent.com/7869766/168530873-e67f7a66-9712-419d-ae1f-b1fd83215ce9.png)

**Comment by nanioo** [comment]
刚启动web还能访问，做一个涉及数据库的操作，程序直接down了

**Comment by hanc00l** [comment]
换到原因了，在docker/mysql/conf.d/my.cnf中增加一行：
[mysqld]
max_connections=1000
删除掉mysql的docker镜像重新docker-compose up -d就可


可以对比一下：
这是之前的：
![截屏2022-05-16 17 26 53](https://user-images.githubusercontent.com/12759172/168562644-7b85522e-a946-4d86-b2d8-21713824b3fb.png)
这是修改后的：
![截屏2022-05-16 17 26 44](https://user-images.githubusercontent.com/12759172/168562628-38fde843-7836-4891-99b3-305ae49064cf.png)

修改的release文件我稍后再更新。

**Comment by nanioo** [comment]
我这里mysql是启动不了，docker-compose up -d后就在restarting状态。
按上面方法试过了，也不行。
查了docker日志，报错是没权限
![1](https://user-images.githubusercontent.com/7869766/168710226-4ada3df5-d748-4a07-833e-6cabd5f0be3e.png)
![2](https://user-images.githubusercontent.com/7869766/168710239-c451dd09-abb0-4881-9cb7-9d8085319dab.png)

**Comment by nanioo** [comment]
![3](https://user-images.githubusercontent.com/7869766/168710401-cc206726-319e-49b8-bd01-ff41c68f0ad2.png)

**Comment by nanioo** [comment]
https://blog.csdn.net/Kingtu_linux/article/details/105852403解决了，参考这个，在docker-compose.yml mysql里加了一个privileged: true

**Comment by nanioo** [comment]
可能原因是操作系统不是ubuntu
