### ISSUE TITLE
添加任务失败!

### ISSUE THREAD

**Issue by RuanLang0777** [hanc00l/nemo_go#27]
这是为啥? 无法进行扫描
![image](https://user-images.githubusercontent.com/53397197/170405842-e1592e45-5916-4610-b583-0f49794f0d55.png)

**Comment by hanc00l** [comment]
应该是添加任务到rabbitmq队列失败。环境你是怎么使用和配置的说一下，我们一起分析一下。

**Comment by RuanLang0777** [comment]
我使用分别构建Server与Worker的Docker安装方式 配置都是默认的

**Comment by RuanLang0777** [comment]
系统使用的centos7

**Comment by hanc00l** [comment]
需要修改conf/worker.yml配置文件中，RPC的IP、authkey与rabbitmq的IP、用户和密码，这里host要指向你本机ip地址，默认是127.0.0.1是docker的话就指向docker本身了，所以worker没法与server通信了。
      ```bash
       
     # rpc配置
      rpc:
        host: x.x.x.x(server所在的vps地址）
        authKey: ZduibTKhcbb6Pi8W
      # 消息中间件配置
      rabbitmq:
        host: x.x.x.x(server所在的vps地址）
        username: nemo
        password: nemo2020
```

**Comment by RuanLang0777** [comment]
VPS IP配置是正确的 ![image](https://user-images.githubusercontent.com/53397197/172516349-785a00f4-eb22-40b0-aeae-8fcb76781032.png)

**Comment by hanc00l** [comment]
请参考文档https://github.com/hanc00l/nemo_go/blob/main/docs/docker.md，需要对参数进行配置。
 
<img width="1552" alt="截屏2022-06-08 12 49 24" src="https://user-images.githubusercontent.com/12759172/172534304-939668c3-5b69-4d82-9ecf-070d3991b16b.png">
<img width="1552" alt="截屏2022-06-08 12 49 31" src="https://user-images.githubusercontent.com/12759172/172534312-cf031675-7d90-45f6-9634-68856a05b8e5.png">
