### ISSUE TITLE
端口扫描

### ISSUE THREAD

**Issue by 3hm1ly** [hanc00l/nemo_go#3]
小建议
建议端口扫描采用masscan+nmap结合的方式扫描
masscan探测端口存活，nmap探测存活端口指纹提高效率和准确率

**Comment by hanc00l** [comment]
不错的想法，之前也考虑到，只是自己一直没有这方面的需求；近期我把这个功能加到代码里。

**Comment by hanc00l** [comment]
已更新v2.4.3。
