### ISSUE TITLE
能否支持fsan扫描结果中的漏洞信息

### ISSUE THREAD

**Issue by regoo** [hanc00l/nemo_go#30]
支持导入fscan扫描结果是个挺好的功能，但目前是不是不支持识别fscan扫描结果中的漏洞为vulnerability

**Comment by hanc00l** [comment]
好像是的，我看看能不能把fscan的结果导入到vulernability里的。

**Comment by hanc00l** [comment]
v2.5.1已更新，将fscan扫描结果中的漏洞导入为vulnerability。

**Comment by regoo** [comment]
楼主好迅速，马上更新试试
