### ISSUE TITLE
mac m1  docker 启动服务异常

### ISSUE THREAD

**Issue by guchaya** [hanc00l/nemo_go#31]
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/105160978/172001809-624dc08b-ff06-4ef7-bd11-6d2824a3dda8.png">
由于是使用arm 芯片我改了一下配置中的mysql 正常启动服务，但是启动服务之后却无法正常使用
<img width="771" alt="image" src="https://user-images.githubusercontent.com/105160978/172002165-32a60fab-f6f7-4022-a8b8-1005f95c1995.png">
辛苦大佬，希望能够回复我 谢谢。

**Comment by hanc00l** [comment]
一是确认是不是从release中下载的nemo_linux_amd64.tar解压后进行docker-compose的，如果是从git拉起的源文件是没有编译二进制文件的，之前有同学遇到的问题是这种情况。二是可以用docker exec进docker里看看server是否正常启动。

**Comment by guchaya** [comment]
<img width="887" alt="image" src="https://user-images.githubusercontent.com/105160978/173327453-b7c71edc-e5d6-417e-a3a8-d635f16bc218.png">
新出现问题 
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/105160978/173327584-c36ab867-a6fa-414c-9c7e-bfff20de96f2.png">
希望大佬回复一下

**Comment by hanc00l** [comment]
很抱歉我刚才注意到你是mac的M1，目前我所有的测试都是基于x86架构的，因为我没有M1的mac所以也无法去测试；所以建议你作为纯使用的话可以考虑x86的VPS或虚拟机里，如果想在M1平台上运行、或者自己修改代码，其实也很简单，只要修改一下golang编译为M1支持的平台（可以自行 google一下）即可，毕竟golang是支持跨平台编译的。
