### ISSUE TITLE
权限拒绝，web没起来

### ISSUE THREAD

**Issue by coopliu** [hanc00l/nemo_go#34]
ubuntu20

<img width="1159" alt="1" src="https://user-images.githubusercontent.com/55048424/175301856-872947ef-9101-4117-a491-256c26dbf347.png">

**Comment by hanc00l** [comment]
请确认是下载release的打包的nemo_linux_amd64.tar包解压后，用docker-compose进行构建；如果是用git clone或从github.com下载的zip包，是不包含编译后的可执行文件的。以前有同学遇到这种情况的。
如果还是有问题，可以提供一下docker构建的详细情况，看是哪一步报错了。

**Comment by coopliu** [comment]
感谢师傅，之前开错机器了，开得是centos8的机器，换了一台ubuntu的就好啦～
