### ISSUE TITLE
WARN[0000] Found orphan containers docker-compose报错 5000端口无法访问

### ISSUE THREAD

**Issue by Crazy-FuQing** [hanc00l/nemo_go#35]
hanc00l师傅你好    WARN[0000] Found orphan containers ([nemo-server rabbitmq mysql]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
![image](https://user-images.githubusercontent.com/46838021/175966635-eaeb6264-404e-48ad-8f42-7e542373609a.png)
看似服务起来了 但是无法访问web
![image](https://user-images.githubusercontent.com/46838021/175967130-6f2adfdb-40d4-45e6-bdf7-2c505c47e509.png)
![image](https://user-images.githubusercontent.com/46838021/175967266-6487a063-3868-4828-8bf7-0ccf18e41d60.png)

**Comment by hanc00l** [comment]
不知道是你用的release里下载的tar包，还是直接从github下载的源码，源码的话需要自己编译二进制文件的。

**Comment by sobinge** [comment]
我访问5000也是进不了网站容器，进入docker.server容器里面查看，web是启动的，感觉5000端口没有映射出来
