### ISSUE TITLE
难题

### ISSUE THREAD

**Issue by jinzezhi** [hanc00l/nemo_go#39]
![image](https://user-images.githubusercontent.com/93123422/183415510-43baf158-ce93-4702-8fdd-8a3351062547.png)
师傅可以帮忙看一下配置文件吗 我根据文档进行了配置 但是结果还是这样

**Comment by hanc00l** [comment]
把具体情况说一下嘛，部署方式以及配置文件，不然不知道问题出在哪儿

**Comment by jinzezhi** [comment]
> 把具体情况说一下嘛，部署方式以及配置文件，不然不知道问题出在哪儿

使用的第二种方法：构建Server与Worker的Docker
在vps上部署的，我觉得应该是配置文件的问题 我根据师傅的文档进行了配置 但是还是这样的结果 ，能否加师傅vx 师傅帮我看一下配置文件呢

**Comment by hanc00l** [comment]
OK，你留一下vx号我加你。

**Comment by jinzezhi** [comment]
tna5757
