### ISSUE TITLE
为什么Nemo增加了任务一直处于create状态呢

### ISSUE THREAD

**Issue by fengzirock** [hanc00l/nemo_go#4]
为什么Nemo增加了任务一直处于create状态呢
![image](https://user-images.githubusercontent.com/59859409/138311568-2c2d11a5-1f5c-4c1a-aa12-2bd5aed91e9d.png)

**Comment by hanc00l** [comment]
任务下发和执行是异步的，server创建了任务后，需要worker来执行；你需要启动一个或多个worker_linux_amd64，worker通过从消息中间件中获取任务后才能执行任务。

**Comment by fengzirock** [comment]
终于解决了 我在docker官网https://docs.docker.com/engine/install/ubuntu/ 重新装了一遍最新版就可以了

**Comment by hanc00l** [comment]
太好了。如果临时或短时使用，用docker方便；如果长期使用，建议还是考虑在vps上安装，并且多个worker分布式运行。
