### ISSUE TITLE
根据分构说明docker部署，配置都是对的，但是连接的还是本地的rabbitmq

### ISSUE THREAD

**Issue by liszero** [hanc00l/nemo_go#42]
<img width="564" alt="image" src="https://user-images.githubusercontent.com/37371029/186316122-0195f24f-e9d1-46e8-acf2-c540e07b3be3.png">
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/37371029/186316730-4dee3fdc-a6fb-4c5b-a509-e4c8ef275f26.png">

**Comment by liszero** [comment]
已经修改了conf/server.yml和worker.yml，docker-compose.server.yml

**Comment by hanc00l** [comment]
先修改配置文件，再用docker-compose构建；如果已构建了，用docker image先删除。

**Comment by Conanjun** [comment]
> 先修改配置文件，再用docker-compose构建；如果已构建了，用docker image先删除。

文件同步的问题，worker经常连接上服务端后就被覆盖为127了

**Comment by 2021Kfzz1** [comment]
我也遇到这个问题了

**Comment by hanc00l** [comment]
server端如果默认是mysql、rabbitmq和web在同一个docker环境的话，是不需要修改server.yml中的ip地址的（为了安全建议改一下密码），并且默认ip地址用的是docker的主机名mysql和rabbitmq。worker需要远程连接到rabbitmq以及rpc通信，需要将worker.yml中的地址改为server所在的vps的外部（或可通信）地址。
如果有问题，可以私下发配置文件到邮件到han2008@qq.com我看看，或者进一步沟通。

**Comment by AlanWalkBill123** [comment]
我也遇到了同样的问题，而且在压缩包解压后配置好了conf/worker.yml 使用docker-compose构建的时候进容器查看配置并无发生变化
