### ISSUE TITLE
结果导出

### ISSUE THREAD

**Issue by jiangdada6** [hanc00l/nemo_go#48]
师傅好，请问扫描结果这么导出呢

**Comment by hanc00l** [comment]
单个任务的扫描结果，是保存为JSON格式的，可以自己查看和自己解析转换需要的数据；资产有一个“统计”功能，主要是用于便于将资产用于其它工具的使用，统计了资产的C段、IP地址及端口，不是把所有资产进行全部导出。
<img width="1264" alt="截屏2022-09-22 10 31 04" src="https://user-images.githubusercontent.com/12759172/191645686-937321c1-077c-44cd-aefd-9ce570da482d.png">
<img width="1772" alt="截屏2022-09-22 10 31 38" src="https://user-images.githubusercontent.com/12759172/191645705-40eff1ec-1096-4b09-9d51-b76d840281de.png">
