### ISSUE TITLE
域名泛解析问题

### ISSUE THREAD

**Issue by jiangdada6** [hanc00l/nemo_go#49]
![20220921180115](https://user-images.githubusercontent.com/50139422/191476327-347d59b8-8c93-49ef-8e95-9053ba0312c3.jpg)

**Comment by hanc00l** [comment]
这个问题我也是第一次遇到。nemo的域名任务主要来源于以下几个方面：通过subfinder被动扫描、用massdns爆破和通过第三方平台，会产生域名泛解析最大的可能是massdns的域名爆破（我看了字典里有006、030等子域名）。不过我仔细检查了massdns代码和在本地作了测试，massdns是有域名泛解析过滤的，按道理应该不会出现。

<img width="1904" alt="截屏2022-09-22 11 14 17" src="https://user-images.githubusercontent.com/12759172/191651059-c24b9eb2-d47a-46fa-aa7a-24cfc947b0b6.png">
<img width="1351" alt="截屏2022-09-22 11 10 56" src="https://user-images.githubusercontent.com/12759172/191651026-90392820-b820-4ce8-a758-d86dd70aa2d5.png">
单独测试massdns代码

<img width="1560" alt="截屏2022-09-22 11 13 54" src="https://user-images.githubusercontent.com/12759172/191651036-e32cbece-1035-4a5b-828c-a94129909486.png">
<img width="1904" alt="截屏2022-09-22 11 15 46" src="https://user-images.githubusercontent.com/12759172/191651044-976fc3ac-8d83-41e4-a8bb-02d7defd0879.png">
测试nemo

所以不太清楚你出现的这个问题，是出现在哪个环节，根据你提供的信息我也无法定位。
