### ISSUE TITLE
go build 报错了

### ISSUE THREAD

**Issue by Conanjun** [hanc00l/nemo_go#50]
<img width="638" alt="image" src="https://user-images.githubusercontent.com/7765655/191708451-ec0aef8a-fef3-4959-b546-b3bce810e669.png">

**Comment by hanc00l** [comment]
https://blog.csdn.net/weixin_43372552/article/details/111703543
http://www.wu.run/2021/05/16/checksum-mismatch-error/
https://www.google.com.hk/search?q=go+build+this+downloads+does+not+math+an+earlier+download&oq=go+build+this+downloads+does+not+math+an+earlier+download&aqs=chrome..69i57j69i64l2.26491j0j15&sourceid=chrome&ie=UTF-8

<img width="1008" alt="截屏2022-09-23 10 03 01" src="https://user-images.githubusercontent.com/12759172/191879923-bd7110ab-78d4-4cc3-9b3b-b595d5cbfeca.png">
<img width="1276" alt="截屏2022-09-23 10 03 22" src="https://user-images.githubusercontent.com/12759172/191879928-3c919d70-c1e9-469a-aff9-4bae244fd372.png">
