### ISSUE TITLE
子域名扫描完成后 不显示结果

### ISSUE THREAD

**Issue by RuanLang0777** [hanc00l/nemo_go#51]
任务扫描成完成后domain不显示结果
![image](https://user-images.githubusercontent.com/53397197/192137707-a78e681d-c92a-40fc-bda0-9a983553ad6b.png)
![image](https://user-images.githubusercontent.com/53397197/192137714-34b4c88c-91ed-4c5e-8b9c-dff8460c369d.png)

**Comment by hanc00l** [comment]
对不起，我也无法根据你提供的情况作出判断是哪里出了问题。

**Comment by RuanLang0777** [comment]
扫描完子域名不显示结果
