### ISSUE TITLE
功能添加建议

### ISSUE THREAD

**Issue by Conanjun** [hanc00l/nemo_go#53]
1. 支持oneforall扫描结果导入
2. 漏洞扫描支持输入某个组织，这样子可以巡检已经保存的对应组织的资产

**Comment by hanc00l** [comment]
好建议已收到，近期会增加类似的功能。

**Comment by hanc00l** [comment]
v2.7-2.8已增加XSCAN功能，可以巡检已经保存的对应组织的资产，可以测试一下是否满足要求；建议将oneforall的子域名放到nemo里执行一次指纹识别，单独导入意义不是太大。
