### ISSUE TITLE
功能添加建议

### ISSUE THREAD

**Issue by zjhzjhhh** [hanc00l/nemo_go#57]
师傅你好，希望添加一个一键导出domain的功能

**Comment by hanc00l** [comment]
<img width="594" alt="截屏2022-12-02 15 37 19" src="https://user-images.githubusercontent.com/12759172/205240410-d4ec68be-10cf-43ca-8e95-5bee9e98e7ca.png">

“功能”-“统计”可以导出domain及相关的统计，可以试试看能否满足要求。

**Comment by zjhzjhhh** [comment]
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/64487620/205242027-8d699708-b0ce-4320-b085-7e12c67e207a.png">
功能-统计处点击后一直转圈圈访问不了

**Comment by hanc00l** [comment]
统计导出的结果和显示的查询结果数量是一样的，我不确定是不是数量太多了的原因，你可以先筛选一下只保留几条看能不能导出（我测试的情况都是数量不太多）；如果查询结果数量太多可能主要压力还是在mysql会做大量的查询和合并。你可以试试看，并分析一下原因，我看能不能改进。
