### ISSUE TITLE
单容器部署容易挂

### ISSUE THREAD

**Issue by coopliu** [hanc00l/nemo_go#59]
4h4g的机器，单容器部署，只有一个worker，跑一个子域名几分钟服务就挂了，CPU直接满，然后服务器登陆不上去，web界面进不去
![image](https://user-images.githubusercontent.com/55048424/206661748-f9bd98ec-a46b-4b49-a91d-0e652095e738.png)
![image](https://user-images.githubusercontent.com/55048424/206661996-4f3700d8-ed36-4a8e-9cc4-e920553855ae.png)

**Comment by hanc00l** [comment]
v2.8.2修复了httpx内存缓存泄露问题，欢迎尝试。

**Comment by hanc00l** [comment]
v2.8.3增加按worker的CPU及内存数量设置不同的性能模式（HighPerformance：4核4G内存及以上），欢迎测试。
