### ISSUE TITLE
v2.8.2版本xray扫描bug

### ISSUE THREAD

**Issue by Mespoding** [hanc00l/nemo_go#60]
版本：v2.8.2
bug描述：docker部署后/opt/nemo下和thirdparty下的config.yaml存在格式错误，造成使用xray时会报load config error, json: unsupported type: map yaml错误导致无法正常扫描
临时解决：删除上述两个地方的config.yaml文件使用xray重新生成解决

**Comment by hanc00l** [comment]
感谢提醒！
这个是我一个小失误。docker用的linux版本的Xray是旧的1.8.2；/opt/nemo下的config.yaml文件是上个2.6.1版本测试window下的nemo时使用了最新的1.9.3版本生成的，这两个版本的xray的配置文件变化太大不兼容所以会出问题。
因为xray文件太大，因此打算从下一个版本更新时，源码里不再更新和提供二进制文件了；打包生成的文件我会单独放最新版本的xray到tar包里；当前版本的xray和配置文件建议大家先自己下载放进去，并生成配置文件再构建docker。

**Comment by hanc00l** [comment]
已在v2.8.3的release里修复该bug。

**Comment by Mespoding** [comment]
我试了一下v2.8.3，好像xray和nuclei都扫不出漏洞，进容器看了一下，创建漏洞验证任务之后，并没有xray和nuclei的进程起来
