### ISSUE TITLE
arm64_linux

### ISSUE THREAD

**Issue by HKTangyuan** [hanc00l/nemo_go#61]
能否提供arm64_linux编译文件

**Comment by hanc00l** [comment]
go代码理论上支持多平台编译和运行，nemo由于调用了一些第三方二进制程序（见下列表）实现一些功能，因此需手动添加对应平台的二进制文件；已在最新的代码里提供了多平台调用的二进制文件规则（可参考fileutils.go代码）；因此需要有其它平台的需求请自行编译并生成，并将对应的平台的二进制文件放在thirdparty对应目录下。
nemo调用的第三方二进制文件：
1、observer_ward
2、xray
3、nuclei
4、massdns

编译命令可参考build.sh或package.sh两个文件。

**Comment by hanc00l** [comment]
https://github.com/hanc00l/nemo_go/commit/a2020f1431f602090091f3df00c80220916c7e22
