### ISSUE TITLE
I can't install 

### ISSUE THREAD

**Issue by hieroo** [hanc00l/nemo_go#62]
Hello dear i can't install 

nemo        | time="2022-12-28 16:35:41" level=info msg="Broker failed with error: Dial error: dial tcp 172.20.0.4:5672: connect: connection refused"
rabbitmq    | 2022-12-28 08:35:41.641878+00:00 [info] <0.630.0> accepting AMQP connection <0.630.0> (172.20.0.6:35210 -> 172.20.0.4:5672)
rabbitmq    | 2022-12-28 08:35:41.643550+00:00 [info] <0.630.0> connection <0.630.0> (172.20.0.6:35210 -> 172.20.0.4:5672): user 'guest' authenticated and granted access to vhost '/'
nemo        | time="2022-12-28 16:35:41" level=info msg="[*] Waiting for messages. To exit press CTRL+C"
rabbitmq    | 2022-12-28 08:35:55.510823+00:00 [info] <0.650.0> accepting AMQP connection <0.650.0> (172.20.0.1:42044 -> 172.20.0.4:5672)
rabbitmq    | 2022-12-28 08:35:55.510982+00:00 [error] <0.650.0> closing AMQP connection <0.650.0> (172.20.0.1:42044 -> 172.20.0.4:5672):
rabbitmq    | 2022-12-28 08:35:55.510982+00:00 [error] <0.650.0> {bad_header,<<"GET / HT">>}
rabbitmq    | 2022-12-28 08:35:56.548844+00:00 [info] <0.655.0> accepting AMQP connection <0.655.0> (172.20.0.1:42058 -> 172.20.0.4:5672)
rabbitmq    | 2022-12-28 08:35:56.548991+00:00 [error] <0.655.0> closing AMQP connection <0.655.0> (172.20.0.1:42058 -> 172.20.0.4:5672):
rabbitmq    | 2022-12-28 08:35:56.548991+00:00 [error] <0.655.0> {bad_header,<<"GET / HT">>}
rabbitmq    | 2022-12-28 08:36:01.566729+00:00 [info] <0.660.0> accepting AMQP connection <0.660.0> (172.20.0.1:46996 -> 172.20.0.4:5672)
rabbitmq    | 2022-12-28 08:36:01.566846+00:00 [error] <0.660.0> closing AMQP connection <0.660.0> (172.20.0.1:46996 -> 172.20.0.4:5672):
rabbitmq    | 2022-12-28 08:36:01.566846+00:00 [error] <0.660.0> {bad_header,<<"GET / HT">>}
rabbitmq    | 2022-12-28 08:36:31.583370+00:00 [info] <0.665.0> accepting AMQP connection <0.665.0> (172.20.0.1:44114 -> 172.20.0.4:5672)
rabbitmq    | 2022-12-28 08:36:31.583561+00:00 [error] <0.665.0> closing AMQP connection <0.665.0> (172.20.0.1:44114 -> 172.20.0.4:5672):
rabbitmq    | 2022-12-28 08:36:31.583561+00:00 [error] <0.665.0> {bad_header,<<"GET / HT">>}

**Comment by hanc00l** [comment]
I think the problem is rabbitmq's user ,"guest" for rabbitmq only accepted for localhost(127.0.0.1). If your rabbitmq and server dont't run in localhost,you should create another user (for example:nemo). 
[This is a reference docs](https://github.com/hanc00l/nemo_go/blob/main/docs/install_linux.md)
