### ISSUE TITLE
功能添加建议

### ISSUE THREAD

**Issue by HKTangyuan** [hanc00l/nemo_go#64]
希望能够像qingscan一样能够支持自定义工具扫描
功能参考：https://wiki.qingscan.site/shi-yong-jiao-cheng/zi-ding-yi-gong-ju

**Comment by hanc00l** [comment]
目前的想法是Nemo是一个简单的资产收集和管理的小工具（“平台”、“系统”都算不上），更多的聚焦在资产信息的收集工具和手段，以及为下一步渗透测试、实战攻防作好参考。漏洞的扫描和利用，只是集成专业了相关工具，并且也只是作为资产的一个辅助。目前的代码主要还是满足个人及同事在实际工作中最主要的需求来写的，因能力、精力和时间有限，我们也知道可能无法满足所有人的功能需求；如果大家有自己的一些更好的想法以及自己的需求，欢迎fork后进行扩展；如果使用中遇到了Bug也欢迎提出issue后我们尽量能解决。
