### ISSUE TITLE
v2.8.3使用问题汇总

### ISSUE THREAD

**Issue by Mespoding** [hanc00l/nemo_go#65]
版本：v2.8.3
安装环境：kali 2022 2C4G虚拟机
部署模式：单容器部署
问题1：在页面点击重启worker或者后台重启nemo容器后，worker就起不来了，只能恢复快照或者重新部署；
问题2：在没有任何任务执行的情况下worker_linux_am的CPU占用一直在45%左右；
问题3：xray、nuclei批量漏洞验证功能无法使用，提交漏洞验证任务后后台无xray进程启动，nuclei有进程启动但是检测不出漏洞（weblogic环境测试）

**Comment by hanc00l** [comment]
问题1应该是文件同步导致的，server下的worker.yml文件会被同步到worker，因此server下的worker.yml应与worker保持一致；
问题2我还没有遇到这个情况，建议看排查一下；
问题3不太确定，因时间和精力原因漏洞验证只在本地和公司做了部份测试，未进行大范围的稳定性和可靠性测试，欢迎测试和提供问题建议。
