### ISSUE TITLE
您好，请问有导出结果的功能嘛😊

### ISSUE THREAD

**Issue by R1ck415** [hanc00l/nemo_go#66]

**Comment by R1ck415** [comment]
还有就是fscan在worker里面，在容易报毒

**Comment by R1ck415** [comment]
> _No description provided._

就想导出站点，但是结果的json文件名不好遍历

**Comment by hanc00l** [comment]
目前没有导出功能，有一个简单的“统计”功能；如果经常需要导出全站数据，建议你写个python脚本直接从数据库里读数据然后整理为你自己想要的格式，数据库的表和结构挺简单的，可以参考源码看看。

**Comment by R1ck415** [comment]
师傅，用docker做sever，work直接搭建，创建任务卡在了CREATED，没有下发任务

**Comment by hanc00l** [comment]
在dashboard里，能不能看到worker？CREATED状态是任务已创建了，但没有worker执行，要么是worker没起来，要么是rabbitmq消息队列通讯有问题。

**Comment by R1ck415** [comment]
没有worker，单个启动可以，分布式不行

**Comment by R1ck415** [comment]
![image](https://user-images.githubusercontent.com/65207395/230765923-0a327f35-98e4-45b8-b7ca-07492dd42516.png)
![image](https://user-images.githubusercontent.com/65207395/230765945-f1073d6f-2a7d-4fa5-97f7-e4254df81f13.png)
![image](https://user-images.githubusercontent.com/65207395/230765954-c93fe89c-817b-4ee3-967d-7f195948bba9.png)
