### ISSUE TITLE
Potential dependency inconsistency

### ISSUE THREAD

**Issue by Ben131-Go** [hanc00l/nemo_go#67]
## Dependency line:
github.com/hanc00l/nemo_go --> [github.com/beego/beego](https://github.com/hanc00l/nemo_go/blob/main/go.mod#L8) --> [github.com/gomodule/redigo](https://github.com/hanc00l/nemo_go/blob/main/go.mod#L111) <br>
github.com/beego/beego v2.0.6 --> github.com/gomodule/redigo v1.8.8<br>
<https://github.com/beego/beego/blob/v2.0.6/go.mod#L79>

## Background
Repo `github.com/beego/beego` at version `v2.0.6` uses replace directive to pin dependency `github.com/gomodule/redigo` to version `v1.8.8`.<br>
According to [Go Modules wikis](https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive), `replace` directives in modules other than the `main module` are ignored when building the main module.
It means such replace usage in dependency's go.mod cannot be inherited when building main module. And it turns out that `hanc00l/nemo_go` indirectly relies on `gomodule/redigo@v2.0.0`, which is different from the pinned version `beego/beego` needed.<br>
><https://github.com/hanc00l/nemo_go/blob/main/go.mod>(Line 111)
```Go
github.com/gomodule/redigo v2.0.0+incompatible // indirect
```

><https://github.com/beego/beego/blob/v2.0.6/go.mod>(line 17&79)
```Go
github.com/gomodule/redigo v2.0.0+incompatible
replace github.com/gomodule/redigo => github.com/gomodule/redigo v1.8.8
```
So this is just a reminder in the hope that you can notice such an inconsistency.
### 1. Bump the version of dependency `github.com/beego/beego`
You may try upgrading dependency `github.com/beego/beego` to a newer version, which may have eliminated the use of this directive.

### 2. Add the same replace rule to your go.mod
```Go
replace github.com/gomodule/redigo => github.com/gomodule/redigo v1.8.8
```

**Comment by hanc00l** [comment]
Thanks!
