### ISSUE TITLE
添加任务失败! 未选择当前的工作空间！

### ISSUE THREAD

**Issue by HiIK-666** [hanc00l/nemo_go#69]
![1678171084273](https://user-images.githubusercontent.com/69377487/223342118-6545fe3f-63f1-40d5-909f-14399eb2b5b9.jpg)
![image](https://user-images.githubusercontent.com/69377487/223342428-56c62681-9408-4388-84c3-2e11f5b99166.png)

**Comment by HiIK-666** [comment]
用户中的工作空间也已经勾选

**Comment by hanc00l** [comment]
建议为不同性质的工作建立“工作空间”，同时建立一个或多个用户并与其关联（用户权限可以是管理员或普通用户），这样在登录后会自动关联相应的工作空间。

工作空间和多用户的目的，是为了进一步满足实战中的多种场景、多个项目与多个用户的需求，做到项目和资源的一个隔离。

**Comment by HiIK-666** [comment]
![image](https://user-images.githubusercontent.com/69377487/223353798-550c02f1-0378-4399-920b-0d65df1b303e.png)
我的右上角并没有，而且我发现除了超级管理员可以登录，管理员和普通用户都无法登录

**Comment by hanc00l** [comment]
右上角并没有切换框的话，是不是之前用过使用过以前版本的Nemo，这样的话需要清除一下浏览器的缓存。
“除了超级管理员可以登录，管理员和普通用户都无法登录”，原因可能是没有给新建的用户设置工作空间。

<img width="1704" alt="iShot_2023-03-07_15 36 30" src="https://user-images.githubusercontent.com/12759172/223355551-3b2f6ef5-1543-4a16-bf7a-18d4155ae948.png">
<img width="1772" alt="iShot_2023-03-07_15 36 51" src="https://user-images.githubusercontent.com/12759172/223355566-f9cc0c59-3971-4cf7-b9ed-3e8fc5f2bf6f.png">

**Comment by HiIK-666** [comment]
解决了感谢
