### ISSUE TITLE
docker 搭建成功访问5000端口显示502

### ISSUE THREAD

**Issue by L0ading-blog** [hanc00l/nemo_go#7]

**Comment by hanc00l** [comment]
docker目前我测试了多个版本均正常，请检查：
1、nemo使用的端口是否被本地占用（3306、5672、5000、5001）；
2、如果以前构造过建议删除原来构建的image；
3、建议更新docker版本；

建议通过docker exec -it xxx sh进入docker环境中，用curl localhost:5000看看是否报错。

**Comment by L0adinggg** [comment]
curl后发现
curl: (7) Failed to connect to localhost port 5000: Connection refused

**Comment by L0adinggg** [comment]
![image](https://user-images.githubusercontent.com/55682875/145340480-6b673dec-72fe-40e6-b722-a311535603c5.png)
这个为docker ps截图

**Comment by hanc00l** [comment]
在docker环境里用netstat -ant看看是否有5000端口，ps aux看看server_linux_amd64是否有进程。

**Comment by L0adinggg** [comment]
![image](https://user-images.githubusercontent.com/55682875/145352357-2a17d722-0a53-4593-ac3e-604e683c4d4f.png)
哈哈哈。都没有，是什么原因呢

**Comment by hanc00l** [comment]
哈哈，我知道了，你是git clone后构建docker的，仓库里只有代码没有二进制文件，你可以build.sh自己先构建，或者下载release里的tar包解压后构建。

**Comment by L0adinggg** [comment]
不对呀，俺是release构建的
![image](https://user-images.githubusercontent.com/55682875/145362885-e905afaa-3238-41a3-b555-569432a86b6d.png)

**Comment by hanc00l** [comment]
你在docker里的/opt/nemo，看看有没有两个文件，如果有的话就手工运行一下；如果没有，重新下一下release里tar包，将原来的docker image删掉重新构建一下试试。

**Comment by L0adinggg** [comment]
![image](https://user-images.githubusercontent.com/55682875/145745860-3ea264f7-147a-4368-bb51-c76026e59101.png)
没有opt目录

**Comment by L0adinggg** [comment]
重新下载release 进行构建以后还是这个问题，您那边要是没问题的话 估计是我的阿里云的问题

**Comment by hanc00l** [comment]
我晚上也找了一台阿里云上测试了docker能正常使用，同时顺更优化了docker-compose.yml文件。建议你从release里下载v2.4.8的nemo_linux_amd64.tar包后执行：
```
mkdir nemo
tar xvf nemo_linux_amd64.tar -C nemo
cd nemo
docker-compose up -d
```
