### ISSUE TITLE
docker部署后进去无法登录

### ISSUE THREAD

**Issue by admi-n** [hanc00l/nemo_go#70]
server.yml
![image](https://user-images.githubusercontent.com/34176629/225379499-0d9cf404-5f32-46bf-bc07-d8f390d62e6d.png)
worker.yml
![image](https://user-images.githubusercontent.com/34176629/225379645-0b381d50-5977-4adc-9fec-2bacab9b0088.png)
输入账户密码但是无法登录
![image](https://user-images.githubusercontent.com/34176629/225380315-45aab50b-7c8f-49ce-bae6-ca56e5f212f0.png)

**Comment by hanc00l** [comment]
默认登录用户名nemo、默认密码是nemo

**Comment by ep113** [comment]
忘记密码怎么办，使用默认密码登录后 修改了密码无法登录
