### ISSUE TITLE
Fofa收集域名Bug

### ISSUE THREAD

**Issue by pdToTbq** [hanc00l/nemo_go#72]
Fofa收集域名好像有点问题
![图片](https://user-images.githubusercontent.com/97932168/228234714-1862876c-3940-4477-bbc8-4bfb5a305193.png)
一直返回的都是空的
![图片](https://user-images.githubusercontent.com/97932168/228235055-b29afe35-4a6c-46c8-a675-862b11fd43ca.png)
有配置api key
![图片](https://user-images.githubusercontent.com/97932168/228235290-28432795-bc59-40c8-a84e-d91a9064fd34.png)
并且这里验证是通过的
![图片](https://user-images.githubusercontent.com/97932168/228235464-ffb688c3-a2b1-410f-9bbf-13e3ec27defe.png)

**Comment by hanc00l** [comment]
我测试了一下fofa的接口功能都正常。“测试API”是在server端调用fofa功能进行测试的，而任务执行fofa是由worker端执行的，测试OK表明key是没问题的；worker执行不成功，是不是worker里的配置文件conf/worker.yml里配置的key有问题？

<img width="1125" alt="iShot_2023-03-29_23 54 34" src="https://user-images.githubusercontent.com/12759172/228597187-c159a0fb-d2ef-4ccc-a388-6f51cba6c48d.png">

**Comment by pdToTbq** [comment]
非常感谢，我在worker.yml中重新配置然后在重启了以下貌似可以了
