### ISSUE TITLE
nemo_windows_amd64.tar中的两个exe文件怎么使用

### ISSUE THREAD

**Issue by jack-She1l** [hanc00l/nemo_go#73]
nemo_windows_amd64.tar中的两个exe文件怎么使用

**Comment by hanc00l** [comment]
这是window平台使用Nemo的执行文件，使用方法和linux是一样的（得益于go的跨平台性）。不过相关的依赖（比如nmap、masscan、chrome以及mysql、rabbitmq等）也是需要自己安装好的。
