### ISSUE TITLE
配置subfinder的key不生效

### ISSUE THREAD

**Issue by 0nion1** [hanc00l/nemo_go#75]
你好，配置了subfinder不生效
![image](https://user-images.githubusercontent.com/53221874/229292197-36963ce4-753b-44f4-88d6-91996bac6586.png)

并且前后端任务显示有问题
<img width="1631" alt="image" src="https://user-images.githubusercontent.com/53221874/229292219-875bbdf7-5e27-43c5-a7d1-ca2378f9e798.png">

**Comment by hanc00l** [comment]
“subfinder的key不生效”不太明白是什么意思，请具体一点，因为我没有相关的api的key所以也没有测试过，如果方便的话可以提供一两个key我测试一下。
“并且前后端任务显示有问题”的原因是有一个checkDomainResolveResult(&resultDomainScan)，去除结果中无域名解析A或CNAME记录的域名。
<img width="965" alt="iShot_2023-04-02_10 02 31" src="https://user-images.githubusercontent.com/12759172/229327088-482a9919-a34f-45cb-a111-51752a0b5bb9.png">

**Comment by 0nion1** [comment]
我已经在nemo/thirdparty/dict/provider-config.yml 配置好了所有的key，但是我用nemo_go去跑的话会获得15个或者18个，但是我本地调用config去跑的话会获得84个，那么就有可能配置的subfinder的key没有生效。
<img width="880" alt="image" src="https://user-images.githubusercontent.com/53221874/229332727-e87036ba-b473-4b6e-bf91-d113685f0714.png">

**Comment by 0nion1** [comment]
不是特定的key不生效是所有的key都没有生效

**Comment by hanc00l** [comment]
感谢测试和提出的问题，bug已找到了，经过跟踪subfinder项目的源码，发现provider-config.yml确实需要手工加载。目前已找到原因和加入了代码，近期会和一些功能一起更新。
<img width="941" alt="iShot_2023-04-04_10 44 08" src="https://user-images.githubusercontent.com/12759172/229674661-2089b813-b42e-428c-a265-99754a4b82d1.png">
<img width="1071" alt="iShot_2023-04-04_10 44 59" src="https://user-images.githubusercontent.com/12759172/229674709-e1c1bbce-14a0-4064-9073-56d637ef4aa2.png">
