### ISSUE TITLE
新建xscan中IP的ip端口和组织的ip端口有什么区别吗

### ISSUE THREAD

**Issue by jack-She1l** [hanc00l/nemo_go#77]
![image](https://user-images.githubusercontent.com/65006918/230259810-59849313-5596-4923-be51-12ffb6460ed1.png)
![image](https://user-images.githubusercontent.com/65006918/230259888-7432e580-97dd-41c2-8344-3d154cd91982.png)

**Comment by hanc00l** [comment]
没有区别的是一样的。xscan中读取指定组织关联的IP资产，对这些资产的IP端口（就是任务里设的）进行扫描、指纹识别以及漏洞扫描等。

**Comment by jack-She1l** [comment]
好的，谢谢
