### ISSUE TITLE
创建的任务直接出错

### ISSUE THREAD

**Issue by akin520** [hanc00l/nemo_go#8]
![image](https://user-images.githubusercontent.com/1317859/145374408-0b0bedc1-84fa-4bf5-aac1-833c183a7646.png)

**Comment by hanc00l** [comment]
任务没有写到数据库里去，是不是数据库有问题？web端任务里能不能看到数据？

**Comment by akin520** [comment]
页面上显示添加成功，你这么一说，我看了一下，表好像没有创建，需要单独创建表吗，数据配置的都没问题，用命令行能连

**Comment by akin520** [comment]
找到了，我不是用的dokcer，没有看到这导入这一步
