### ISSUE TITLE
api token测试不通过

### ISSUE THREAD

**Issue by xiaosaoba** [hanc00l/nemo_go#80]
配置设置里面配置fofa的邮箱和api保存，然后点击测试api报错失败

![image](https://user-images.githubusercontent.com/26709924/231718390-637b4332-0cc5-459f-8f95-b91632d682dd.png)

**Comment by hanc00l** [comment]
api测试是在server端进行的，因此配置的key要确保在server的conf/worker.yml中有；（实际执行任务用的是worker端自己的配置文件，一般建议通过文件同步功能在server端配置后自动同步过去）。
