### ISSUE TITLE
分布式部署修改密码能简化一下嘛

### ISSUE THREAD

**Issue by R1ck415** [hanc00l/nemo_go#82]
师傅，还有就是多台部署的时候会有无worker的问题
![image](https://user-images.githubusercontent.com/65207395/231941754-45eae0df-c22f-4411-8b9c-7fc6d44e5742.png)
![image](https://user-images.githubusercontent.com/65207395/231941764-b8350dee-a22b-4102-87f2-8474d56e6a94.png)
![image](https://user-images.githubusercontent.com/65207395/231941775-6f20d20b-56c4-4ba4-bd2b-3c7278763cb3.png)

**Comment by hanc00l** [comment]
建议如果想持续使用nemo的话，server和worker直接安装在虚拟机或vps里，server因为需要安装rabbitmq、mysql麻烦一点，worker其实只需要安装nmap、masscan和chrome就可以了，也挺方便的。可参考docs/install_linux.md。

**Comment by R1ck415** [comment]
> 建议如果想持续使用nemo的话，server和worker直接安装在虚拟机或vps里，server因为需要安装rabbitmq、mysql麻烦一点，worker其实只需要安装nmap、masscan和chrome就可以了，也挺方便的。可参考docs/install_linux.md。

嗯嗯

**Comment by R1ck415** [comment]
师傅，界面验证码功能有关闭选项嘛，想外部调用/domain-list和/ip-list接口，还有就是url信息的接口

**Comment by R1ck415** [comment]
还有个bug是分布式执行任务时候，fofa请求过快
![image](https://user-images.githubusercontent.com/65207395/232363744-554e9cc9-b8a6-4976-9256-d1781c5ed7fc.png)

**Comment by hanc00l** [comment]
> 师傅，界面验证码功能有关闭选项嘛，想外部调用/domain-list和/ip-list接口，还有就是想有个url-lit信息的接口

暂时没有关闭的功能，你可以在代码里注释掉这几行然后重新编译就可以了。
<img width="701" alt="iShot_2023-04-17_21 29 35" src="https://user-images.githubusercontent.com/12759172/232498897-eb98c6f7-1f16-4b4c-8495-5ac95bba9618.png">

还有一个方法就是v2.9是新增了一个webapi接口的（目前功能还在不断完善中），目的就是为前后端分离提供支持；有兴趣可以看看pkd/webapi，以及build_api.sh，同时提供了swagger测试UI。
