### ISSUE TITLE
docker nemo启动成功无法访问5000

### ISSUE THREAD

**Issue by qiangshaozhang** [hanc00l/nemo_go#83]
尝试过2.91 2.90 2.83 
docker-compose up -d 无任何报错成功后 
netstat -lntp 端口也有5000端口
使用浏览器和curl都无法访问

**Comment by ximeng610** [comment]
解决了吗我也是这个问题
helpme

**Comment by minghuinet** [comment]
+1

**Comment by sh1yeichen** [comment]
开了代理就有可能访问不成功
