### ISSUE TITLE
worker没起来啊

### ISSUE THREAD

**Issue by tonmonkey** [hanc00l/nemo_go#85]
![image](https://user-images.githubusercontent.com/84943423/233828697-a44ca370-1bb0-457b-af8f-7b50bdb91218.png)
![image](https://user-images.githubusercontent.com/84943423/233828715-52490e24-fe3a-4108-8632-5b81a5b51929.png)
![image](https://user-images.githubusercontent.com/84943423/233828738-720739e2-7019-4a0f-a6c2-2bce0bea368f.png)
![image](https://user-images.githubusercontent.com/84943423/233828752-58312cf2-abed-4c65-9947-e17e938dacbb.png)

**Comment by tonmonkey** [comment]
日志也是空的，没有记录
![image](https://user-images.githubusercontent.com/84943423/233828873-a8620ed8-258b-4674-9896-3e7b5de3158e.png)

**Comment by tonmonkey** [comment]
看server日志应该是数据库没连接，但不知道为啥没连接
![image](https://user-images.githubusercontent.com/84943423/233829157-dc9eeb95-8deb-4c24-9ec2-dc7ba15dd3bf.png)

**Comment by hanc00l** [comment]
确实一下conf目录下的server.yml和worker.yml的配置是否正确，特别是ip地址、以及用户名和密码

**Comment by tonmonkey** [comment]
都检查了，重启后还是不行，页面还弹出如下告警：
![image](https://user-images.githubusercontent.com/84943423/233830848-f5c9bb59-4a1d-41bf-9935-4046237474c0.png)

**Comment by AlanWalkBill123** [comment]
> 都检查了，重新启动后还是不行，页面还弹出如下警告： ![图像](https://user-images.githubusercontent.com/84943423/233830848-f5c9bb59-4a1d-41bf-9935-4046237474c0.png)

我之前也是，你现在好了吗

**Comment by tonmonkey** [comment]
> > 都检查了，重新启动后还是不行，页面还弹出如下警告： ![图像](https://user-images.githubusercontent.com/84943423/233830848-f5c9bb59-4a1d-41bf-9935-4046237474c0.png)
> 
> 我之前也是，你现在好了吗

没有~~~，等作者解答了:)我看数据库里面有数据，就是worker没起来，是不是bug哦

**Comment by hanc00l** [comment]
请把主机包括docker的ip地址、以及server/worker的配置文件发出来看看，敏感的信息（如IP、用户名和密码）可以打马一下。

**Comment by tonmonkey** [comment]
server.yml如下：
![image](https://user-images.githubusercontent.com/84943423/233968578-06b5241d-6c05-4b8a-b386-f51d71ddfdac.png)
worker.yml如下：
![image](https://user-images.githubusercontent.com/84943423/233968768-658438dc-02e2-4031-923e-5db3c46e5fd5.png)

**Comment by tonmonkey** [comment]
server如下：
![image](https://user-images.githubusercontent.com/84943423/233969228-3345bf0b-e336-406c-9b06-e459bc919f74.png)

worker如下：
![image](https://user-images.githubusercontent.com/84943423/233969139-cf0bd1f9-5430-473c-bac8-c94d5248f2dd.png)

**Comment by hanc00l** [comment]
server.yml里数据库地址127.0.0.1要改成"mysql"或者vps地址，因为对于server跑在docker里的；本来在Dockerfile里是自动替换的，不知道为什么没有生效？
<img width="479" alt="iShot_2023-04-24_22 03 04" src="https://user-images.githubusercontent.com/12759172/234020576-f8c7f90d-d0c7-4ba2-a1b0-cbf3572a42cf.png">
<img width="675" alt="iShot_2023-04-24_22 03 29" src="https://user-images.githubusercontent.com/12759172/234020603-a64ae4f4-ca9c-4262-b552-4dea0f3bc88e.png">

**Comment by hanc00l** [comment]
worker.yml里的配置里，rpc与fileSync的host地址，也要指向vps地址，这样才能和server正常通信。（可以想象一下worker也是史上在docker里的）。

**Comment by tonmonkey** [comment]
好的，谢谢作者拉

**Comment by hanc00l** [comment]
文档和手册确实没有太详细，等时间和精力允许我再把文档完善一下，还请见谅。

**Comment by AlanWalkBill123** [comment]
测试了一下，其实server.xml里面的mysql和rabbitmq就是写127和localhost就行，毕竟有link链接了。主要是这个链接貌似不太稳定，有时候大任务的时候worker会掉线，看日志就显示[error] failed to initialize database, got error dial tcp 127.0.0.1:3306: connect: connection refused ，得重启。不知道这个是性能问题还是docker的link不稳定

**Comment by hanc00l** [comment]
> 测试了一下，其实server.xml里面的mysql和rabbitmq就是写127和localhost就行，毕竟有link链接了。主要是这个链接貌似不太稳定，有时候大任务的时候worker会掉线，看日志就显示[error] failed to initialize database, got error dial tcp 127.0.0.1:3306: connect: connection refused ，得重启。不知道这个是性能问题还是docker的link不稳定

docker的稳定性确实没有去深入测试过；docker的方式比较适合临时使用，如果觉得有必要持续使用，建议还是安装到vps或虚拟机上，特别是任务并发高了之的性能在docker比较受限；server安装主要是rabbitmq和mysql两个组件，worker用ubuntu安装其实还是比较方便的（nmap/masscan/chrome），可参考docs里的文档。

**Comment by hanc00l** [comment]
等有时间了看能不能写个自动化的安装脚本并完善一下文档
