### ISSUE TITLE
导入nemo.sql出错，输入密码响应

### ISSUE THREAD

**Issue by CaoaiLWT** [hanc00l/nemo_go#86]
![image](https://user-images.githubusercontent.com/85109943/233950601-6b7b99d1-71bf-462c-b3d9-5b79aef7b143.png)

**Comment by CaoaiLWT** [comment]
![image](https://user-images.githubusercontent.com/85109943/234046659-80c9a94b-e540-4d81-9530-6e2d9082a9fa.png)
话说钉钉的推送是只需要输入token就行吗，起不来呀

**Comment by CaoaiLWT** [comment]
![image](https://user-images.githubusercontent.com/85109943/234051758-5592c3cd-783f-4ed8-9b6e-84ff0ae223a0.png)
终于到这步了，但是总是出现则个报错

**Comment by CaoaiLWT** [comment]
![image](https://user-images.githubusercontent.com/85109943/234055018-0bb7213d-c7ea-482f-ad9f-36579fbdc0e2.png)
前一张图是设置密码时后面出现#，然后被识别为闭合，导致密码不完整，出现的错误，然后现在这个错误请问需要这么解决

**Comment by hanc00l** [comment]
这个应该是rabbitmq的用户和密码不对，在server要增加一个用户并设置权限，并在worker.yml中配置。

<img width="751" alt="iShot_2023-04-25_08 59 23" src="https://user-images.githubusercontent.com/12759172/234149371-256f0a47-f719-47b6-9d3d-ddb90265688f.png">

这里要改成对应的server的地址和配置的用户名密码
<img width="452" alt="iShot_2023-04-25_09 01 37" src="https://user-images.githubusercontent.com/12759172/234149501-dfc72990-a852-4485-8387-b61f14a89644.png">

**Comment by CaoaiLWT** [comment]
好的，谢谢，我试试，我最近也在学自动化渗透



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月25日(星期二) 上午9:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hanc00l/nemo_go] 导入nemo.sql出错，输入密码响应 (Issue #86)





 
这个应该是rabbitmq的用户和密码不对，在server要增加一个用户并设置权限，并在worker.yml中配置。
 

 
这里要改成对应的server的地址和配置的用户名密码

**Comment by CaoaiLWT** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hanc00l/nemo_go"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月25日(星期二) 上午9:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hanc00l/nemo_go] 导入nemo.sql出错，输入密码响应 (Issue #86)





 
这个应该是rabbitmq的用户和密码不对，在server要增加一个用户并设置权限，并在worker.yml中配置。
 

 
这里要改成对应的server的地址和配置的用户名密码

**Comment by CaoaiLWT** [comment]
登录密码是rabbitmq的吗，还是默认的nemo

**Comment by CaoaiLWT** [comment]
> 这个应该是rabbitmq的用户和密码不对，在server要增加一个用户并设置权限，并在worker.yml中配置。
> 
> <img alt="iShot_2023-04-25_08 59 23" width="751" src="https://user-images.githubusercontent.com/12759172/234149371-256f0a47-f719-47b6-9d3d-ddb90265688f.png">
> 
> 这里要改成对应的server的地址和配置的用户名密码 <img alt="iShot_2023-04-25_09 01 37" width="452" src="https://user-images.githubusercontent.com/12759172/234149501-dfc72990-a852-4485-8387-b61f14a89644.png">
> 
> 另外补充一下，rabbitmq的默认的guest/guest，是只允许在rabbitmq的localhost使用（这是rabbitmq的规定）。

大佬是否能创建一个微信或者qq的交流群
