### ISSUE TITLE
是否可以增加资产的导出

### ISSUE THREAD

**Issue by qingyun00** [hanc00l/nemo_go#88]
在扫描结束后是否可以增加资产的导出，包括IP、端口信息、URL信息等等

**Comment by hanc00l** [comment]
https://github.com/hanc00l/nemo_go/issues/66#issuecomment-1407226220
https://github.com/hanc00l/nemo_go/issues/48#issuecomment-1254440424

**Comment by hanc00l** [comment]
v2.10.0已增加导出ip及domain资产功能。
