### ISSUE TITLE
domainscan卡住

### ISSUE THREAD

**Issue by xiao-zhu-zhu** [hanc00l/nemo_go#89]
domainscan会卡住
<img width="1112" alt="图片" src="https://github.com/hanc00l/nemo_go/assets/85468097/865ff448-f580-48c9-8312-0c58a0ee537b">

**Comment by hanc00l** [comment]
这个任务量有点大，子域名爆破和被动枚举都比较占用资源，“2/872/1253”表示有总共有1253个任务（包括完成和未完成的），有2个正在执行，有872个任务待运行；从截图里感觉每个域名任务都有很多任务，估计是资源不足；建议优化一下任务，同时增加足够的worker分布式同时执行。
