### ISSUE TITLE
好像还不太稳

### ISSUE THREAD

**Issue by lapalipi** [hanc00l/nemo_go#9]
2021/12/10 10:12:02 github.com/hanc00l/nemo_go/pkg/db/conn.go:39
[error] failed to initialize database, got error dial tcp 127.0.0.1:3306: connect: connection refused

**Comment by 3hm1ly** [comment]
+1 任务一多数据库就会connection refused

**Comment by hanc00l** [comment]
在很久前就发现的确是有这个问题，尚不清楚是否是依赖的GORM的性能问题，还是我的代码使用或配置引起的，我也在一直跟踪该问题。如果有好的解决办法或想法可以一起改进。

**Comment by hanc00l** [comment]
v2.4.21已修复一个数据库操作连接没有及时释放的BUG，建议可以更新看看。
