### ISSUE TITLE
请问安装好后，api接口怎么访问呢

### ISSUE THREAD

**Issue by yanghuanfirst** [hanc00l/nemo_go#90]
现在利用docker部署好了，web也能访问了，但是我想要访问api接口，应该怎么访问呢。现在访问127.0.0.1:5000/v1/login/login等接口都是404。

**Comment by hanc00l** [comment]
目前api接口功能还处于测试阶段没有发布二进制文件，如果需要使用的话需要自己通过源码编译和生成二进制文件。

1、下载nemo_go的源代码；
2、安装beego：cd nemo_go && go get -u github.com/beego/bee/v2
3、运行build_api.sh将生成二进制文件；
4、提供了一个swagger-ui用于调试接口（需要在pkg/conf/config.go将var RunMode = Debug取消注释，并注释掉var RunMode = Release），url为/swagger）
5、api服务默认端口为5003；如果与webserver同时运行的话，要加参数：-nf和-nr关闭文件同步和RPC服务。

**Comment by yanghuanfirst** [comment]
> 目前api接口功能还处于测试阶段没有发布二进制文件，如果需要使用的话需要自己通过源码编译和生成二进制文件。
> 
> 1、下载nemo_go的源代码； 2、安装beego：cd nemo_go && go get -u github.com/beego/bee/v2 3、运行build_api.sh将生成二进制文件； 4、提供了一个swagger-ui用于调试接口（需要在pkg/conf/config.go将var RunMode = Debug取消注释，并注释掉var RunMode = Release），url为/swagger） 5、api服务默认端口为5003；如果与webserver同时运行的话，要加参数：-nf和-nr关闭文件同步和RPC服务。

非常感谢您的问答，但是现在出现了新问题？麻烦有空的时候看下。最后请问生成的二进制文件在哪个目录呢？
![image](https://github.com/hanc00l/nemo_go/assets/42403329/7582b496-dd1d-4e85-81a9-6e909d7f06d2)
