### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by HiIK-666** [hanc00l/nemo_go#99]
本地部署 ubuntu22 没用docker的 扫描端口一会就断网了，子域名也是  手动nmap扫描1000的速度并不会断网

**Comment by hanc00l** [comment]
不太清楚你的“本地部署”的具体情况是什么，是外网独立VPS、云主机（是不是有可能因流量太大导致被限流？）？还是内网独立服务器？
我本人使用经验是在内网独立服务器部署，三年来都没有出现这种情况，建议先排查一下环境，以及nemo进程的cpu及网络流量等具体情况，如果能找到原因也可以给大家以后的类似的问题提供参考。

**Comment by HiIK-666** [comment]
内网独立服务器，我测试后发下可能是我电脑的问题我用另外一台是不会断网的，应该并不是nemo的问题
